name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://user:password@localhost:5432/testdb
      JWT_SECRET: supersecret
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: backend_v1/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: backend_v1

      - name: Generate Prisma client
        run: pnpm run db:client
        working-directory: backend_v1

      - name: Typecheck
        run: pnpm run typecheck
        working-directory: backend_v1

      - name: Build
        run: pnpm run build
        working-directory: backend_v1

      - name: Remove dist
        run: rm -rf dist
        working-directory: backend_v1

      - name: Run migrations
        run: pnpm run db:deploy
        working-directory: backend_v1

      - name: Run integration tests
        run: pnpm run test
        working-directory: backend_v1
